// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCXkEqW5VoGKZoVwFocf-HGbkzJUYRIrBA',
    appId: '1:22085137042:web:5da0d874f9baec1f04ac4b',
    messagingSenderId: '22085137042',
    projectId: 'techboom-4f80d',
    authDomain: 'techboom-4f80d.firebaseapp.com',
    storageBucket: 'techboom-4f80d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRIZW5uXRQ0BoB9QNX4xlNYZcekoNVHFo',
    appId: '1:22085137042:android:1732e70457dbedee04ac4b',
    messagingSenderId: '22085137042',
    projectId: 'techboom-4f80d',
    storageBucket: 'techboom-4f80d.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIc3yBkDl5ynfK60-Hdbnq14qZSRY-vC4',
    appId: '1:22085137042:ios:f5f3df60a5ce9bfe04ac4b',
    messagingSenderId: '22085137042',
    projectId: 'techboom-4f80d',
    storageBucket: 'techboom-4f80d.firebasestorage.app',
    iosBundleId: 'com.example.tbGame',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAIc3yBkDl5ynfK60-Hdbnq14qZSRY-vC4',
    appId: '1:22085137042:ios:f5f3df60a5ce9bfe04ac4b',
    messagingSenderId: '22085137042',
    projectId: 'techboom-4f80d',
    storageBucket: 'techboom-4f80d.firebasestorage.app',
    iosBundleId: 'com.example.tbGame',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCXkEqW5VoGKZoVwFocf-HGbkzJUYRIrBA',
    appId: '1:22085137042:web:acb0be3319a3d3b504ac4b',
    messagingSenderId: '22085137042',
    projectId: 'techboom-4f80d',
    authDomain: 'techboom-4f80d.firebaseapp.com',
    storageBucket: 'techboom-4f80d.firebasestorage.app',
  );
}
